theme: jekyll-theme-minimal
title: AI-Resilient Interfaces: a framework for critiquing AI-powered systems that prioritizes giving users the interfaces that actually allow them to notice and have the context to accurately judge AI choices made on their behalf.
description: Project lead: Elena Glassman assisted by Rain YeYang, Jonathan Kummerfeld, Ziwei Gu, Chelse Swoopes, Andy Haupt, and Mozes Jacobs.
